# Generated by Django 5.2.7 on 2025-11-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('highlight', models.TextField(blank=True, db_column='highlights', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productreviews',
                'managed': False,
            },
        ),
    ]
