# Generated by Django 5.2.8 on 2025-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_delete_productreview'),
        ('recommendations', '0002_productfeaturesnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mlentitymap',
            new_name='ml_entity_m_entity__79b057_idx',
            old_name='recommend_ml_enti_6efd5b_idx',
        ),
        migrations.RenameIndex(
            model_name='mlentitymap',
            new_name='ml_entity_m_entity__79d96a_idx',
            old_name='recommend_ml_enti_f38bb7_idx',
        ),
        migrations.AddIndex(
            model_name='productfeaturesnapshot',
            index=models.Index(fields=['external_id'], name='ml_product__externa_5e0526_idx'),
        ),
    ]
